<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Licit.BiddingService.Application\Licit.BiddingService.Application.csproj" />
    <ProjectReference Include="..\Licit.BiddingService.Infrastructure\Licit.BiddingService.Infrastructure.csproj" />
    <ProjectReference Include="..\Licit.BiddingService.Persistence\Licit.BiddingService.Persistence.csproj" />
  </ItemGroup>
</Project>
